services:
  portal:
    build: .
    volumes:
      - portal-static-files:/var/data/portal/static
      - portal-media-files:/var/data/portal/media
      - portal-db-files:/var/data/portal/db
    # environment:
    #   DJANGO_DEBUG: true

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/keys/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx/keys/server.key:/etc/ssl/private/server.key:ro
      - ./nginx/keys/server.crt:/etc/ssl/certs/server.crt:ro
      - portal-static-files:/app/static:ro
      - portal-media-files:/app/media:ro
    depends_on:
      - portal

volumes:
  portal-static-files:
  portal-media-files:
  portal-db-files:
